### ISSUE TITLE
DIP version of PETDisk Max

### ISSUE THREAD

**Issue by Jartza** [bitfixer/petdisk-max#5]
Hi,

As you may know, the availability of ATMega1284p in SMD is pretty much non-existing before next year. I noticed though, that Digikey has around 4000 of those in DIP size packages.

So I solved the problem of not getting PETDisk Max myself by designing a DIP version. Some components are SMD and they are all placed underside the board (so you can still order SMD-populated board from JLC for example). I also solved the problem of getting power to the board by designing passthrough to cassette port, where you can take power. Also the PETDisk Max itself has passthrough in the PCB.

I tested this (without ESP-module as I don't have a use for it) and it seems to work :)

If there's any interest, I could drop PCB files & Gerbers here? (I'm still using Eagle, unfortunately haven't had time to really master Kicad yet).

![USER_SCOPED_TEMP_DATA_MSGR_PHOTO_FOR_UPLOAD_1643135858994_6891811305922434785](https://user-images.githubusercontent.com/1577840/151178455-465a5c48-d4ac-4152-be5b-dddebd653bdf.jpeg)

![USER_SCOPED_TEMP_DATA_MSGR_PHOTO_FOR_UPLOAD_1643025300072_6891347588195195010](https://user-images.githubusercontent.com/1577840/151178010-df407f74-088f-4baf-b025-c441948debae.jpeg)

![IMG_20220126_142232589](https://user-images.githubusercontent.com/1577840/151178184-fed4c640-93e8-45a4-91ea-4c3340ba9704.jpg)

**Comment by Jartza** [comment]
![USER_SCOPED_TEMP_DATA_MSGR_PHOTO_FOR_UPLOAD_1643136665219_6891814687478977236](https://user-images.githubusercontent.com/1577840/151179007-11a2ff09-f43c-4610-8264-ec7eb526c24b.jpeg)

**Comment by bitfixer** [comment]
Hi, this is great! Congratulations on the new layout. Would be happy to
have this on the repo, if you like you could mail those to me and I will
put them up, or send me a PR for it.
Good solution with the power from the cassette port, this was what I had
for the original PETdisk (before it was MAX) and works well. Do you have
the data lines from the cassette port brought over to the other board? I
had this and they were connected to a couple of spare pins on the MCU,
always intended to implement a cassette loader this way but never did it.
The chip shortage does seem to have struck with the atmega chips, seems
like there have been none available for a couple of months at least. A
preview of the next version of the PETdisk MAX - I decided to switch over
from using an ATMega1284 to using an ESP32 module in the next board
revision, which seems to be widely available right now. This means only one
microcontroller on the board and no separate wifi module, saves a bit of
board cost as well as being a more capable microcontroller in general. Got
the firmware ported over to the new platform, but kept everything almost
completely the same so future firmware updates will be built for both
platforms.
Again congratulations on the board design and happy to put it up on the
repo. Thanks,
- Mike
***@***.***

**Comment by Jartza** [comment]
Hi. I can make a pull request :)

I only brought in the 5V and GND lines, actually both 3 times (as those 6-pin crimpable connectors for flat cable are easy to crimp) . But of course as there's Eagle files available, it's easy to modify them.

**Comment by Jartza** [comment]
I think actually Kicad opens Eagle files without issues as well.

I now also verified that the ESP-01 is working with this DIP-version. The only differences are that this is missing the UART pins and reset-button but those should be easy to add.

**Comment by Jartza** [comment]
https://github.com/bitfixer/petdisk-max/pull/6

**Comment by Jartza** [comment]
Tape adapter:

https://github.com/bitfixer/petdisk-max/pull/8

**Comment by Jartza** [comment]
Two pull requests as I did fumble something and couldn't get them into single one 😄

**Comment by Jartza** [comment]
Looks like the PRs have been merged, thanks. I'm closing this issue.
